INSERT INTO departments (department_name)
VALUES 
    ('Sales'),
    ('Engineering'),
    ('Legal'),
    ('Finance'),
    ('Brand & Digital');

INSERT INTO roles (title, salary, department_id)
VALUES 
    ('Sales Agent', 50000, 1),
    ('Sales Manager', 60000, 1),
    ('Engineering Team Director', 120000, 2),
    ('Senior Developer', 100000, 2),
    ('Jr Developer', 70000, 2),
    ('Legal Team Lead', 95000, 3),
    ('Lawyer', 90000, 3),
    ('Senior Accountant', 65000, 4),
    ('Jr Accountant', 55000, 4),
    ('Digital Design Manager', 80000, 5),
    ('Digital Designer', 70000, 5);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
('Geoff', 'Rawstron', 9, NULL),
('Aurea', 'Durrad', 5, NULL),
('Anabelle', 'Peteri', 4, NULL),
('Skippy', 'Cochet', 1, NULL),
('Windy', 'Odney', 4, NULL),
('Nona', 'Tander', 5, NULL),
('Crichton', 'Taffe', 11, NULL),
('Delilah', 'Waterhowse', 7, NULL),
('Milty', 'Bunyard', 5, NULL),
('Humfrid', 'Varian', 9, NULL),
('Chandler', 'Hendrich', 1, NULL),
('Daren', 'Digginson', 7, NULL),
('Izabel', 'Kilvington', 5, NULL),
('Jan', 'Olivas', 10, NULL),
('Barnabe', 'Caltera', 1, NULL),
('Skippy', 'Lissandre', 8, NULL),
('Dulci', 'Peevor', 5, NULL),
('Terrijo', 'Gandy', 9, NULL),
('Jammie', 'Burcher', 7, NULL),
('Kasey', 'Halden', 7, NULL),
('Luz', 'Buten', 7, NULL),
('Phaidra', 'Fyldes', 11, NULL),
('Selinda', 'Fretson', 9, NULL),
('Matthew', 'Rubenov', 7, NULL),
('Karim', 'Prosch', 1, NULL),
('Rockey', 'Decroix', 9, NULL),
('Demetris', 'Farn', 2, NULL),
('Kennie', 'Arnott', 1, NULL),
('Gustav', 'Dunstall', 3, NULL),
('Chad', 'Dairton', 4, NULL),
('Portia', 'O''Henery', 10, NULL),
('Melina', 'Bernlin', 5, NULL),
('Skippie', 'Dennes', 11, NULL),
('Dru', 'Parramore', 1, NULL),
('Early', 'Bending', 11, NULL),
('Jacynth', 'Bilton', 1, NULL),
('Othella', 'Grimbaldeston', 4, NULL),
('Sallyann', 'Tacon', 8, NULL),
('Erinn', 'Rhymer', 1, NULL),
('Etienne', 'Gullivan', 5, NULL),
('Sosanna', 'Wragge', 4, NULL),
('Helenka', 'Drury', 6, NULL),
('My', 'Budgeon', 1, NULL),
('Brendon', 'Kinane', 1, NULL),
('Torie', 'Pellitt', 1, NULL),
('Renaldo', 'Brunel', 5, NULL),
('Giovanna', 'Epple', 2, NULL),
('Douglass', 'Ogers', 2, NULL),
('Willamina', 'Kimbly', 4, NULL),
('Maison', 'Grigorkin', 1, NULL)