INSERT INTO departments (department_name)
VALUES 
    ('Sales'),
    ('Engineering'),
    ('Legal'),
    ('Finance'),
    ('Brand & Digital');

INSERT INTO roles (title, salary, department_id)
VALUES 
    ('Sales Agent', 50000, 1),
    ('Sales Manager', 60000, 1),
    ('Engineering Team Director', 120000, 2),
    ('Senior Developer', 100000, 2),
    ('Mobile App Developer', 85000, 2),
    ('Web App Developer', 85000, 2),
    ('Jr Developer', 70000, 2),
    ('Legal Team Lead', 95000, 3),
    ('Lawyer', 90000, 3),
    ('Senior Accountant', 65000, 4),
    ('Jr Accountant', 55000, 4),
    ('Creative Director', 100000, 5),
    ('Digital Design Manager', 80000, 5),
    ('Digital Designer', 70000, 5),
    ('Jr Digital Designer', 60000, 5),
    ('Copy writer Mangaer', 70000, 5),
    ('Senior Copy writer', 60000, 5),
    ('Jr Copy writer', 50000, 5),
    ('Proof reader', 50000, 5);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
('Blanca', 'Mebes', 9, 5),
('Donella', 'De Giovanni', 7, 4),
('Cleo', 'Wigmore', 9, 5),
('Laureen', 'Kernes', 2, 3),
('Dalis', 'Gammell', 17, 1),
('Quinn', 'Scutchin', 13, 3),
('Marylee', 'Pretious', 11, 3),
('Danella', 'Constable', 12, 1),
('Jarid', 'Knappitt', 11, 5),
('Ignazio', 'Lohering', 17, 5),
('Ibbie', 'Thiese', 16, 4),
('Steward', 'Lansley', 8, 2),
('Kerrie', 'Dawidowsky', 14, 5),
('Fayth', 'Stallworth', 7, 4),
('Torry', 'Caroll', 11, 5),
('Corrina', 'Root', 5, 1),
('Andris', 'Goor', 8, 1),
('Eleanor', 'Cradey', 17, 4),
('Jesselyn', 'Pratton', 8, 2),
('Jaime', 'Robilart', 8, 5),
('Tomi', 'Beeson', 4, 1),
('Christal', 'Bridal', 5, 3),
('Codee', 'Kollasch', 3, 2),
('Domini', 'Brimmacombe', 4, 2),
('Layney', 'Evenett', 2, 5),
('Prentiss', 'Cush', 15, 4),
('Hyacinthe', 'Lepope', 4, 3),
('Livia', 'Avrahamov', 1, 5),
('Lydie', 'Petchey', 6, 3),
('Jean', 'Falconar', 13, 5),
('Bridgette', 'Jobbing', 15, 5),
('Malinda', 'Manwell', 4, 4),
('Caria', 'Hayth', 2, 1),
('Godiva', 'Bonavia', 9, 2),
('Nehemiah', 'Marfe', 7, 3),
('Virgilio', 'Brumby', 14, 4),
('Blake', 'Manchett', 4, 2),
('Zahara', 'Zaniolini', 7, 4),
('Hillard', 'Brettor', 14, 3),
('Mady', 'Entwistle', 15, 1),
('Kipp', 'Woodburn', 3, 3),
('Arlinda', 'Fittall', 18, 4),
('Cristobal', 'Toulch', 3, 4),
('Alexandra', 'Ochiltree', 16, 2),
('Biron', 'Joontjes', 11, 4),
('Rollins', 'Tift', 2, 5),
('Jackie', 'Knellen', 6, 1),
('Doris', 'Croysdale', 6, 5),
('Barny', 'Ditts', 2, 1),
('Lorna', 'Janssens', 4, 4),
('Miltie', 'McCurry', 13, 2),
('Carma', 'Stickel', 8, 5),
('Delmar', 'Pride', 15, 1),
('Floris', 'Guiu', 9, 1),
('Adriane', 'Simondson', 3, 4),
('Odille', 'Woffinden', 6, 2),
('Chev', 'Sperrett', 15, 1),
('Brendon', 'Kolushev', 6, 2),
('Derril', 'Bolley', 4, 2),
('Ethe', 'Chidzoy', 12, 4),
('Steffen', 'Del Monte', 14, 3),
('Sosanna', 'Shaughnessy', 8, 4),
('Franzen', 'Dikles', 15, 1),
('Wilow', 'Trelease', 3, 3),
('Molli', 'Caldwell', 14, 1),
('Finn', 'Dearell', 15, 5),
('Wren', 'Pirkis', 16, 4),
('Butch', 'Forrester', 3, 1),
('Bettine', 'Hasser', 12, 1),
('Casper', 'Muddimer', 16, 2),
('Mitchael', 'Cockrem', 10, 5),
('Nettie', 'Schultes', 7, 3),
('Pietra', 'Blanden', 2, 2),
('Vlad', 'McAdam', 8, 3),
('Dermot', 'McQuade', 12, 1),
('Elisha', 'Skelbeck', 11, 4),
('Syman', 'Vynehall', 10, 1),
('Rodina', 'Leversha', 9, 3),
('Blisse', 'Rahill', 7, 3),
('Elnora', 'Stait', 9, 4),
('Kandace', 'Gregson', 15, 4),
('Crystie', 'O''Sheils', 8, 5),
('Arly', 'Andreucci', 9, 2),
('Issi', 'Feaver', 4, 1),
('Leonardo', 'Bittlestone', 2, 1),
('Donaugh', 'Benedidick', 13, 2),
('Shermy', 'Kidder', 8, 5),
('Gaston', 'McCadden', 14, 5),
('Clement', 'Scamp', 13, 5),
('Juanita', 'Lardiner', 13, 3),
('Karlotta', 'Buxey', 4, 5),
('Reilly', 'Gyenes', 12, 1),
('Jeanne', 'Rogers', 8, 2),
('Arabelle', 'Joscelyne', 16, 2),
('Rogers', 'Assel', 12, 3),
('Darnell', 'Summerley', 15, 4),
('Joshuah', 'Byers', 16, 4),
('Scarlet', 'Heyball', 5, 2),
('Rosy', 'Minchin', 17, 4),
('Gaynor', 'Tack', 5, 5);